using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace SourceGenerators;

[Generator]
internal class DeepCloneGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        AddAttribute(context);

        var attributeValueProvider = context.SyntaxProvider.ForAttributeWithMetadataName("SourceGenerators.DeepCloneAttribute",
            predicate: static (nodeContext, _) => true,
            transform: static (typeContext, _) => (INamedTypeSymbol)typeContext.TargetSymbol);

        context.RegisterSourceOutput(attributeValueProvider, GenerateDeepClonePartial);
    }

    private static void AddAttribute(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context => context.AddSource("DeepCloneAttribute.g.cs",
            """
            // <auto-generated />
            namespace SourceGenerators;

            [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false)]
            public sealed class DeepCloneAttribute : System.Attribute
            {
            }
            """));
    }

    private void GenerateDeepClonePartial(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (!Debugger.IsAttached)
        {
            //Debugger.Launch();
        }
        var namespaceDeclaration = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};\n";

        var classAccessModifier = SyntaxFacts.GetText(classSymbol.DeclaredAccessibility);
        if (!string.IsNullOrEmpty(classAccessModifier))
        {
            classAccessModifier += " ";
        }

        var properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod is not null);

        var cloneableProperties =
            properties
            .Where(p => p.Type is INamedTypeSymbol namedTypeSymbol &&
                        namedTypeSymbol.GetAttributes().Any(attr => attr.AttributeClass?.ToDisplayString() == "SourceGenerators.DeepCloneAttribute"));

        var collectionProperties =
            properties
            .Where(p => (p.Type as INamedTypeSymbol)?.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.ICollection<T>" ||
                p.Type.AllInterfaces.Any(i => i.ToDisplayString().StartsWith("System.Collections.Generic.ICollection<")));

        var cloneableCollectionProperties =
            collectionProperties
            .Where(p => p.Type is INamedTypeSymbol namedTypeSymbol &&
                        namedTypeSymbol.TypeArguments.OfType<INamedTypeSymbol>().Any(ta => ta.GetAttributes().Any(attr => attr.AttributeClass?.ToDisplayString() == "SourceGenerators.DeepCloneAttribute")));

        var valueCollectionProperties =
            collectionProperties
            .Except(cloneableCollectionProperties);

        var valueProperties = properties.Except(cloneableProperties).Except(collectionProperties);

        var source = new StringBuilder();
        source.AppendLine(
            $$"""
            // <auto-generated/>
            using System;

            {{namespaceDeclaration}}
            {{classAccessModifier}}partial class {{classSymbol.Name}}
            {
                public {{classSymbol.Name}} DeepClone()
                {
                    var clone = new {{classSymbol.Name}}();
            """);

        foreach (var property in valueProperties)
        {
            source.AppendLine(Indent($"clone.{property.Name} = this.{property.Name};", 2));
        }

        foreach (var property in cloneableProperties)
        {
            source.AppendLine(Indent($"clone.{property.Name} = this.{property.Name}?.DeepClone();", 2));
        }

        foreach (var property in valueCollectionProperties)
        {
            source.AppendLine(Indent($"clone.{property.Name} = this.{property.Name} is null ? [] : [..this.{property.Name}];", 2));
        }

        foreach (var property in cloneableCollectionProperties)
        {
            source.AppendLine(Indent($"clone.{property.Name} = this.{property.Name} is null ? [] : [..this.{property.Name}.Select(x => x?.DeepClone())];", 2));
        }

        source.AppendLine(
            """
                    return clone;
                }
            }
            """);

        context.AddSource($"{classSymbol.Name}_DeepClone.g.cs", source.ToString());
    }

    private static string Indent(string value, int scopes)
    {
        return new string(' ', scopes * 4) + value;
    }
}
