using Microsoft.CodeAnalysis;

namespace SourceGenerators;

[Generator]
public class MessageGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("MessageProvider.g.cs",
                """
                // <auto-generated/>
                namespace Application;
                
                internal class MessageProvider : IMessageProvider
                {
                    public string GetWelcomeMessage() => "Hello, Source Generator!";
                }
                """);
        });
    }
}