using Microsoft.CodeAnalysis;
using SourceGenerators.JsonSchemas;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace SourceGenerators;

[Generator]
public class SchemaSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var documentationProvider = context.AdditionalTextsProvider
           .Where(static file => file.Path.Contains($"Schemas{Path.DirectorySeparatorChar}Documentation") && file.Path.EndsWith(".json"))
           .SelectMany((file, cancellationToken) => ParseSchema<DocumentationSchema[]>(file.GetText(cancellationToken)!.ToString()));

        var classProvider = context.AdditionalTextsProvider
            .Where(static file => (file.Path.Contains($"Schemas{Path.DirectorySeparatorChar}Models") || file.Path.Contains($"Schemas{Path.DirectorySeparatorChar}Operations")) && file.Path.EndsWith(".json"))
            .SelectMany((file, cancellationToken) => ParseSchema<ClassSchema[]>(file.GetText(cancellationToken)!.ToString()));

        var docs = documentationProvider.Collect();

        var combined = classProvider.Combine(docs);

        context.RegisterSourceOutput(combined, GenerateClassFromSchema);
    }

    private static T ParseSchema<T>(string json)
    {
        return JsonSerializer.Deserialize<T>(json)!;
    }

    private static void GenerateClassFromSchema(SourceProductionContext context, (ClassSchema ClassSchema, ImmutableArray<DocumentationSchema> DocumentationSchema) source)
    {
        var classSource = GenerateClass(source.ClassSchema, source.DocumentationSchema);
        context.AddSource($"{source.ClassSchema.Type}.g.cs", classSource);
    }

    private static string GenerateClass(ClassSchema classSchema, ImmutableArray<DocumentationSchema> docs)
    {
        var source = new StringBuilder();
        source.AppendLine(
            $$"""
            // <auto-generated/>
            namespace {{classSchema.Domain}};

            """);

        var classDocsSchema = docs.FirstOrDefault(d => classSchema.SchemaId != null && d.ReferenceSchemaId == classSchema.SchemaId);
        if (classDocsSchema != null)
        {
            source.AppendLine(
                $$"""
                /// <summary>
                /// {{classDocsSchema.Description}}
                /// <summary/>
                """);
        }

        source.AppendLine(
            $$"""
            public class {{classSchema.Type}}
            """);

        source.Append("{");

        foreach (var propertySchema in classSchema.Properties ?? [])
        {
            source.Append("\n    ");
            var propertyDocsSchema = docs.FirstOrDefault(d => propertySchema.SchemaId != null && d.ReferenceSchemaId == propertySchema.SchemaId);
            var propertySource = GenerateProperty(propertySchema, propertyDocsSchema).Replace("\n", "\n    ");
            source.AppendLine(propertySource);
        }

        source.AppendLine("}");

        return source.ToString();
    }

    private static string GenerateProperty(PropertiesSchema propertySchema, DocumentationSchema? documentationSchema)
    {
        var source = new StringBuilder();

        if (documentationSchema != null)
        {
            source.AppendLine(
                $$"""
                /// <summary>
                /// {{documentationSchema.Description}}
                /// <summary/>
                """);
        }

        var required = propertySchema.Required ? "required " : null;

        source.Append(
            $$"""
            public {{required}}{{propertySchema.Type}} {{propertySchema.Name}} { get; set; }
            """);

        return source.ToString();
    }
}
