using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;

namespace SourceGenerators;

[Generator]
internal class CachingDecoratorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeValueProvider = context.SyntaxProvider.ForAttributeWithMetadataName("Caching.CacheAttribute",
            predicate: static (node, _) => true,
            transform: static (ctx, _) => ctx);

        context.RegisterSourceOutput(attributeValueProvider, GenerateCachingDecorator);
    }

    private void GenerateCachingDecorator(SourceProductionContext context, GeneratorAttributeSyntaxContext syntaxContext)
    {
        var methodDeclaration = (MethodDeclarationSyntax)syntaxContext.TargetNode;
        var innerClassName = GetClassDeclaration(methodDeclaration).GetText();
        var namespaceDeclaration = GetNamespaceDeclaration(methodDeclaration);
        var methodName = methodDeclaration.Identifier.ValueText;

        var parameterVariables = methodDeclaration.ParameterList.Parameters.Select(p => p.Identifier.Value);
        var parameterVariablesStrings = methodDeclaration.ParameterList.Parameters.Select(p => p.Identifier.Value + ".ToString()");

        var source = new StringBuilder();
        source.AppendLine(
            $$"""
            // <auto-generated />
            using System;
            using System.Collections.Generic;

            namespace {{namespaceDeclaration?.Name}};

            public class {{innerClassName}}CachingDecorator
            {
                private readonly {{innerClassName}} _inner;
                private readonly Dictionary<string, object> _cache = new();

                public {{innerClassName}}CachingDecorator({{innerClassName}} inner)
                {
                    _inner = inner;
                }

                {{methodDeclaration.Modifiers}} {{methodDeclaration.ReturnType}} {{methodDeclaration.Identifier.ValueText}}{{methodDeclaration.ParameterList}}
                {
                    var cacheKey = string.Join(",", [{{string.Join(", ", parameterVariablesStrings)}}]);
                    if (_cache.TryGetValue(cacheKey, out var cachedValue))
                    {
                        return ({{methodDeclaration.ReturnType}})cachedValue;
                    }
                    var result = _inner.{{methodDeclaration.Identifier.ValueText}}({{string.Join(", ", parameterVariables)}});
                    _cache[cacheKey] = result;
                    return result;
                }
            """);

        var classDeclaration = (ClassDeclarationSyntax)methodDeclaration.Parent;
        var otherMethods = classDeclaration.Members
            .OfType<MethodDeclarationSyntax>()
            .Where(m => m.Identifier.ValueText != methodName);

        foreach (var method in otherMethods)
        {
            source.AppendLine();
            source.Append(
                $$"""
                    {{method.Modifiers}} {{method.ReturnType}} {{method.Identifier.ValueText}}{{method.ParameterList}}
                    {
                        
                """);
            if (method.ReturnType.ToString() != "void")
            {
                source.Append("return ");
            }
            source.AppendLine($"_inner.{method.Identifier.ValueText}({string.Join(", ", method.ParameterList.Parameters.Select(p => p.Identifier.ValueText))});");
            source.AppendLine("    }");
        }

        source.AppendLine("}");

        context.AddSource($"{GetClassDeclaration(methodDeclaration).Identifier}CachingDecorator.g.cs", source.ToString());
    }


    private NamespaceDeclarationSyntax GetNamespaceDeclaration(SyntaxNode node)
    {
        SyntaxNode current = node;
        while (current != null)
        {
            if (current is NamespaceDeclarationSyntax namespaceDeclaration)
            {
                return namespaceDeclaration;
            }
            current = current.Parent;
        }
        return null;
    }

    private ClassDeclarationSyntax GetClassDeclaration(SyntaxNode node)
    {
        SyntaxNode current = node;
        while (current != null)
        {
            if (current is ClassDeclarationSyntax classDeclaration)
            {
                return classDeclaration;
            }
            current = current.Parent;
        }
        return null;
    }
}
